version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      # Framework gems
      - dependency-name: google-api-python-client
        dependency-type: direct
